---

services:
  laravel:
    build: ./
    command: php artisan serve --host 0.0.0.0 --port 8000 -vvv
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 3ifn336eQ6BrYSaQU4C4
    volumes:
      - "mysql:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=3ifn336eQ6BrYSaQU4C4
      - PMA_ABSOLUTE_URI=http://localhost:8001

volumes:
  mysql:
